# Generated by Django 3.1.1 on 2020-10-29 05:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=5),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='studytime',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='studytime',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'morning'), ('a', 'afternoon'), ('e', 'evening'), ('n', 'night')], default='e', max_length=1),
        ),
        migrations.DeleteModel(
            name='StudyTime',
        ),
    ]
