# Generated by Django 3.1.2 on 2020-10-30 22:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201029_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studytime',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'morning'), ('a', 'afternoon'), ('e', 'evening'), ('n', 'night')], default='e', max_length=10),
        ),
    ]
