# Generated by Django 3.1.1 on 2020-11-13 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20201113_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(blank=True, through='api.Enroll', to=settings.AUTH_USER_MODEL),
        ),
    ]
