# Generated by Django 3.1.1 on 2020-11-13 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20201113_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
